[package]
name = "early_repayment_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
colored = "2.1.0"
pdf-extract = "0.7.9"
walkdir = "2.3.1"
press-btn-continue = "0.2.0"
